version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    command: yarn debug
    ports:
      - 8000:8000
      - 9229:9229
    volumes:
      - .:/app
      - /app/node_modules
